### ISSUE TITLE
Emoji in string causes Jazz to choke

### ISSUE THREAD

**Issue by jeregrine** [meh/jazz#3]
``` elixir
iex> json = %S/{"str": "✔︎"}/
"{\"str\": \"✔︎\"}"
iex> JSON.decode!(json)
# hangs forever and immediately takes 500mb of memory then slowly falls to 100mb
```

Running on elixir 0.12.3 and 0.12.4-dev

**Comment by meh** [comment]
@devinus ^

**Comment by bitwalker** [comment]
I posted this in IRC:

The jazz parser looks like it expects unicode characters in \uXXXX format, if you swap out `"✔︎"` with `"\\u2713"`, it works as expected.

**Comment by bitwalker** [comment]
Found that changing line 245 in https://github.com/meh/jazz/blob/master/lib/json/parser.ex#L244-L246 from 3 to 4 fixes the issue with this particular test case, but my guess is that whole section needs a review.

**Comment by devinus** [comment]
We should add a test.

**Comment by meh** [comment]
@devinus I added a test already in the commit.
